# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Learns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgName', models.CharField(max_length=30)),
                ('shortTitle', models.CharField(max_length=50)),
                ('longTitle', models.TextField()),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employerName', models.CharField(max_length=30)),
                ('startDate', models.DateField()),
                ('title', models.CharField(max_length=30)),
            ],
        ),
    ]
