# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employerName', models.CharField(max_length=30)),
                ('startDate', models.DateField()),
                ('title', models.CharField(max_length=30)),
            ],
        ),
    ]
