# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Learns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgName', models.CharField(max_length=30)),
                ('shortTitle', models.CharField(max_length=50)),
                ('longTitle', models.TextField()),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
