# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Organization'),
        ),
    ]
