# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20161220_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='works',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Organization'),
            preserve_default=False,
        ),
    ]
