# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование игры, Battefield')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='GameProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_nid', models.IntegerField(default=0, unique=True, verbose_name='NID из старой версии сайта')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование игры, Battlefield [PS4]')),
                ('price', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Цена продажи')),
                ('cost', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Закупка')),
                ('stock', models.SmallIntegerField(default=0, verbose_name='Склад')),
                ('canOrder', models.BooleanField(default=False, verbose_name='Под заказ: True - можно заказать даже если склад = 0')),
                ('releaseDate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата выхода')),
                ('commingDate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата поступления')),
                ('cover', models.ImageField(upload_to='gameproduct_covers', verbose_name='Ссылка на обложку')),
                ('used', models.BooleanField(default=False, verbose_name='Игра Б/У?')),
                ('basenid', models.IntegerField(default=0, verbose_name='Nid БАЗЫ из gamebuy')),
                ('gameType', models.SmallIntegerField(blank=True, choices=[(1, 'Коллекционное издание'), (2, 'Сборник'), (3, 'Издание Игра года'), (4, 'Переиздание Platinum'), (5, 'Переиздание Classic'), (6, 'Переиздание Essential'), (7, 'Переиздание Nintendo Selects'), (8, 'Jewel'), (9, 'Специальное издание'), (10, 'Дополнение'), (11, 'Collection'), (12, 'Remaster'), (13, 'Day One Edition'), (100, 'Трилогия'), (101, 'DS')], default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterId', models.SmallIntegerField(blank=True, null=True, verbose_name='Id для группировки')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldId', models.SmallIntegerField(default=0, verbose_name='Id термина на старом сайте')),
                ('title', models.CharField(max_length=100)),
                ('shortTitle', models.CharField(max_length=50, verbose_name='Краткое наименование')),
                ('alias', models.SlugField(verbose_name='URL')),
            ],
        ),
        migrations.AddField(
            model_name='gameproduct',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopbase.LanguageCategory', verbose_name='ссылка на таблицу с языком'),
        ),
        migrations.AddField(
            model_name='gameproduct',
            name='platformCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopbase.PlatformCategory', verbose_name='Термин Платформа'),
        ),
    ]
