# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopbase', '0002_genrecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameproduct',
            name='genre',
            field=models.ManyToManyField(to='shopbase.GenreCategory'),
        ),
    ]
