# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopbase', '0003_gameproduct_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genrecategory',
            name='alias',
            field=models.SlugField(blank=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='genrecategory',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genrecategory',
            name='oldId',
            field=models.SmallIntegerField(default=0, verbose_name='Id термина на старом сайте'),
        ),
    ]
